
spring.application.name=gateway

spring.cloud.gateway.server.webflux.discovery.locator.enabled=false
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

server.port=8085
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.secret=${JWT_SECRET:bWluaGEtY2hhdmUtc2VjcmV0YS1tdWl0by1zZWd1cmEtMjAyNg==}
